language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
services: 
  - postgresql
before_install:
  - psql -c 'create database todos_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage

